import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { JiraIssue, JiraSearchResponse } from './jira.service';

@Injectable({
  providedIn: 'root'
})
export class MockJiraService {
  getIssues(): Observable<JiraSearchResponse> {
    const issues: JiraIssue[] = [
      {
        id: '10001',
        key: 'B2B-1',
        fields: {
          summary: 'Настроить интеграцию с Jira',
          sprintName: 'Sprint 1',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-02-01',
          sprintStartDate: '2026-02-01',
          blockedSince: undefined,
          reopenCount: 1,
          timeInProgressHours: 40,
          timeInReviewHours: 8,
          cycleTimeHours: 60,
          flowEfficiency: 0.8,
          lastStatusChangeAt: '2026-02-10',
          statusChangeCount: 5,
          inReviewSince: '2026-02-08',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10002',
        key: 'B2B-2',
        fields: {
          summary: 'Добавить отображение задач на дашборде',
          sprintName: 'Sprint 1',
          storyPoints: 3,
          plannedInSprint: true,
          addedMidSprint: true,
          createdAt: '2026-02-05',
          sprintStartDate: '2026-02-01',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 16,
          timeInReviewHours: 4,
          cycleTimeHours: 30,
          flowEfficiency: 0.67,
          lastStatusChangeAt: '2026-02-09',
          statusChangeCount: 3,
          inReviewSince: '2026-02-08',
          status: { name: 'To Do' },
          assignee: { displayName: 'Пётр Петров' }
        }
      },
      {
        id: '10003',
        key: 'B2B-3',
        fields: {
          summary: 'Реализовать фильтрацию задач по спринту',
          sprintName: 'Sprint 2',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-02-10',
          sprintStartDate: '2026-02-10',
          blockedSince: '2026-02-15',
          reopenCount: 3,
          timeInProgressHours: 24,
          timeInReviewHours: 12,
          cycleTimeHours: 50,
          flowEfficiency: 0.72,
          lastStatusChangeAt: '2026-02-20',
          statusChangeCount: 8,
          inReviewSince: '2026-02-18',
          status: { name: 'Done' },
          assignee: { displayName: 'Анна Смирнова' }
        }
      },
      {
        id: '10004',
        key: 'B2B-4',
        fields: {
          summary: 'Оптимизировать производительность отчёта по спринтам',
          sprintName: 'Sprint 2',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: true,
          createdAt: '2026-02-12',
          sprintStartDate: '2026-02-10',
          blockedSince: '2026-02-18',
          reopenCount: 2,
          timeInProgressHours: 30,
          timeInReviewHours: 10,
          cycleTimeHours: 70,
          flowEfficiency: 0.57,
          lastStatusChangeAt: '2026-02-22',
          statusChangeCount: 6,
          inReviewSince: '2026-02-19',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10005',
        key: 'B2B-5',
        fields: {
          summary: 'Рефакторинг модуля аутентификации',
          sprintName: 'Sprint 3',
          storyPoints: 3,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-02-20',
          sprintStartDate: '2026-02-20',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 12,
          timeInReviewHours: 4,
          cycleTimeHours: 24,
          flowEfficiency: 0.67,
          lastStatusChangeAt: '2026-02-24',
          statusChangeCount: 2,
          inReviewSince: '2026-02-23',
          status: { name: 'Done' },
          assignee: { displayName: 'Мария Кузнецова' }
        }
      },
      {
        id: '10006',
        key: 'B2B-6',
        fields: {
          summary: 'Добавить логирование ключевых метрик',
          sprintName: 'Sprint 3',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: true,
          createdAt: '2026-02-22',
          sprintStartDate: '2026-02-20',
          blockedSince: undefined,
          reopenCount: 1,
          timeInProgressHours: 20,
          timeInReviewHours: 6,
          cycleTimeHours: 40,
          flowEfficiency: 0.65,
          lastStatusChangeAt: '2026-02-27',
          statusChangeCount: 4,
          inReviewSince: '2026-02-26',
          status: { name: 'In Review' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10007',
        key: 'B2B-7',
        fields: {
          summary: 'Исправить ошибки в отчёте по спринтам',
          sprintName: 'Sprint 3',
          storyPoints: 2,
          plannedInSprint: false,
          addedMidSprint: true,
          createdAt: '2026-02-24',
          sprintStartDate: '2026-02-20',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 8,
          timeInReviewHours: 0,
          cycleTimeHours: 12,
          flowEfficiency: 0.67,
          lastStatusChangeAt: '2026-02-25',
          statusChangeCount: 1,
          inReviewSince: undefined,
          status: { name: 'To Do' },
          assignee: { displayName: 'Пётр Петров' }
        }
      },
      {
        id: '10008',
        key: 'B2B-8',
        fields: {
          summary: 'Добавить экспорт отчётов в CSV',
          sprintName: 'Sprint 4',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-03-01',
          sprintStartDate: '2026-03-01',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 32,
          timeInReviewHours: 6,
          cycleTimeHours: 48,
          flowEfficiency: 0.79,
          lastStatusChangeAt: '2026-03-08',
          statusChangeCount: 5,
          inReviewSince: '2026-03-06',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Анна Смирнова' }
        }
      },
      {
        id: '10009',
        key: 'B2B-9',
        fields: {
          summary: 'Реализовать фильтрацию задач по исполнителю',
          sprintName: 'Sprint 4',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-03-02',
          sprintStartDate: '2026-03-01',
          blockedSince: undefined,
          reopenCount: 2,
          timeInProgressHours: 18,
          timeInReviewHours: 5,
          cycleTimeHours: 36,
          flowEfficiency: 0.64,
          lastStatusChangeAt: '2026-03-07',
          statusChangeCount: 6,
          inReviewSince: '2026-03-05',
          status: { name: 'Done' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10010',
        key: 'B2B-10',
        fields: {
          summary: 'Сделать виджет «Health спринта»',
          sprintName: 'Sprint 4',
          storyPoints: 3,
          plannedInSprint: false,
          addedMidSprint: true,
          createdAt: '2026-03-05',
          sprintStartDate: '2026-03-01',
          blockedSince: '2026-03-07',
          reopenCount: 1,
          timeInProgressHours: 10,
          timeInReviewHours: 3,
          cycleTimeHours: 30,
          flowEfficiency: 0.43,
          lastStatusChangeAt: '2026-03-10',
          statusChangeCount: 4,
          inReviewSince: '2026-03-08',
          status: { name: 'Blocked' },
          assignee: { displayName: 'Мария Кузнецова' }
        }
      },
      {
        id: '10011',
        key: 'B2B-11',
        fields: {
          summary: 'Обновить дизайн страницы дашборда',
          sprintName: 'Sprint 5',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-03-10',
          sprintStartDate: '2026-03-10',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 28,
          timeInReviewHours: 7,
          cycleTimeHours: 50,
          flowEfficiency: 0.7,
          lastStatusChangeAt: '2026-03-16',
          statusChangeCount: 3,
          inReviewSince: '2026-03-15',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Анна Смирнова' }
        }
      },
      {
        id: '10012',
        key: 'B2B-12',
        fields: {
          summary: 'Добавить подсветку проблемных спринтов',
          sprintName: 'Sprint 5',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: true,
          createdAt: '2026-03-12',
          sprintStartDate: '2026-03-10',
          blockedSince: undefined,
          reopenCount: 3,
          timeInProgressHours: 22,
          timeInReviewHours: 6,
          cycleTimeHours: 40,
          flowEfficiency: 0.7,
          lastStatusChangeAt: '2026-03-18',
          statusChangeCount: 7,
          inReviewSince: '2026-03-16',
          status: { name: 'Done' },
          assignee: { displayName: 'Пётр Петров' }
        }
      },
      {
        id: '10013',
        key: 'B2B-13',
        fields: {
          summary: 'Интеграция с системой уведомлений',
          sprintName: 'Sprint 5',
          storyPoints: 13,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-03-13',
          sprintStartDate: '2026-03-10',
          blockedSince: '2026-03-16',
          reopenCount: 1,
          timeInProgressHours: 26,
          timeInReviewHours: 4,
          cycleTimeHours: 60,
          flowEfficiency: 0.5,
          lastStatusChangeAt: '2026-03-22',
          statusChangeCount: 9,
          inReviewSince: '2026-03-19',
          status: { name: 'Blocked' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10014',
        key: 'B2B-14',
        fields: {
          summary: 'Добавить фильтрацию по командам',
          sprintName: 'Sprint 6',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-03-20',
          sprintStartDate: '2026-03-20',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 30,
          timeInReviewHours: 8,
          cycleTimeHours: 55,
          flowEfficiency: 0.69,
          lastStatusChangeAt: '2026-03-26',
          statusChangeCount: 4,
          inReviewSince: '2026-03-25',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Мария Кузнецова' }
        }
      },
      {
        id: '10015',
        key: 'B2B-15',
        fields: {
          summary: 'Починить расчёт Carry-over',
          sprintName: 'Sprint 6',
          storyPoints: 3,
          plannedInSprint: true,
          addedMidSprint: true,
          createdAt: '2026-03-22',
          sprintStartDate: '2026-03-20',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 14,
          timeInReviewHours: 3,
          cycleTimeHours: 28,
          flowEfficiency: 0.61,
          lastStatusChangeAt: '2026-03-27',
          statusChangeCount: 3,
          inReviewSince: '2026-03-26',
          status: { name: 'Done' },
          assignee: { displayName: 'Пётр Петров' }
        }
      },
      {
        id: '10016',
        key: 'B2B-16',
        fields: {
          summary: 'Добавить диаграмму velocity по спринтам',
          sprintName: 'Sprint 6',
          storyPoints: 5,
          plannedInSprint: false,
          addedMidSprint: true,
          createdAt: '2026-03-24',
          sprintStartDate: '2026-03-20',
          blockedSince: undefined,
          reopenCount: 2,
          timeInProgressHours: 16,
          timeInReviewHours: 5,
          cycleTimeHours: 34,
          flowEfficiency: 0.62,
          lastStatusChangeAt: '2026-03-29',
          statusChangeCount: 5,
          inReviewSince: '2026-03-28',
          status: { name: 'In Review' },
          assignee: { displayName: 'Анна Смирнова' }
        }
      },
      {
        id: '10017',
        key: 'B2B-17',
        fields: {
          summary: 'Реализовать фильтрацию задач по типу',
          sprintName: 'Sprint 7',
          storyPoints: 3,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-03-30',
          sprintStartDate: '2026-03-30',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 6,
          timeInReviewHours: 0,
          cycleTimeHours: 10,
          flowEfficiency: 0.6,
          lastStatusChangeAt: '2026-03-31',
          statusChangeCount: 1,
          inReviewSince: undefined,
          status: { name: 'To Do' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10018',
        key: 'B2B-18',
        fields: {
          summary: 'Оптимизировать запросы к Jira API',
          sprintName: 'Sprint 7',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-03-31',
          sprintStartDate: '2026-03-30',
          blockedSince: '2026-04-02',
          reopenCount: 1,
          timeInProgressHours: 18,
          timeInReviewHours: 4,
          cycleTimeHours: 45,
          flowEfficiency: 0.49,
          lastStatusChangeAt: '2026-04-06',
          statusChangeCount: 6,
          inReviewSince: '2026-04-04',
          status: { name: 'Blocked' },
          assignee: { displayName: 'Мария Кузнецова' }
        }
      },
      {
        id: '10019',
        key: 'B2B-19',
        fields: {
          summary: 'Добавить печатную версию отчёта',
          sprintName: 'Sprint 7',
          storyPoints: 5,
          plannedInSprint: false,
          addedMidSprint: true,
          createdAt: '2026-04-01',
          sprintStartDate: '2026-03-30',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 10,
          timeInReviewHours: 2,
          cycleTimeHours: 20,
          flowEfficiency: 0.6,
          lastStatusChangeAt: '2026-04-05',
          statusChangeCount: 2,
          inReviewSince: '2026-04-04',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Пётр Петров' }
        }
      },
      {
        id: '10020',
        key: 'B2B-20',
        fields: {
          summary: 'Сделать мониторинг качества планирования',
          sprintName: 'Sprint 8',
          storyPoints: 13,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-05',
          sprintStartDate: '2026-04-05',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 24,
          timeInReviewHours: 6,
          cycleTimeHours: 40,
          flowEfficiency: 0.75,
          lastStatusChangeAt: '2026-04-10',
          statusChangeCount: 3,
          inReviewSince: '2026-04-08',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10021',
        key: 'B2B-21',
        fields: {
          summary: 'B2B: Настроить алерты по деградации velocity',
          sprintName: 'Sprint 8',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-06',
          sprintStartDate: '2026-04-05',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 10,
          timeInReviewHours: 2,
          cycleTimeHours: 20,
          flowEfficiency: 0.6,
          lastStatusChangeAt: '2026-04-08',
          statusChangeCount: 2,
          inReviewSince: '2026-04-07',
          status: { name: 'In Review' },
          assignee: { displayName: 'Анна Смирнова' }
        }
      },
      {
        id: '10022',
        key: 'B2B-22',
        fields: {
          summary: 'B2B: Добавить отчёт по SLA для заказчиков',
          sprintName: 'Sprint 8',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: true,
          createdAt: '2026-04-07',
          sprintStartDate: '2026-04-05',
          blockedSince: undefined,
          reopenCount: 1,
          timeInProgressHours: 18,
          timeInReviewHours: 4,
          cycleTimeHours: 32,
          flowEfficiency: 0.69,
          lastStatusChangeAt: '2026-04-12',
          statusChangeCount: 4,
          inReviewSince: '2026-04-10',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Пётр Петров' }
        }
      },
      {
        id: '10023',
        key: 'B2B-23',
        fields: {
          summary: 'B2B: Исправить расхождения в расчёте SP',
          sprintName: 'Sprint 8',
          storyPoints: 3,
          plannedInSprint: false,
          addedMidSprint: true,
          createdAt: '2026-04-08',
          sprintStartDate: '2026-04-05',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 6,
          timeInReviewHours: 1,
          cycleTimeHours: 12,
          flowEfficiency: 0.58,
          lastStatusChangeAt: '2026-04-09',
          statusChangeCount: 2,
          inReviewSince: '2026-04-09',
          status: { name: 'Done' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10024',
        key: 'B2B-24',
        fields: {
          summary: 'B2B: Добавить фильтрацию по клиенту',
          sprintName: 'Sprint 9',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-10',
          sprintStartDate: '2026-04-10',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 14,
          timeInReviewHours: 3,
          cycleTimeHours: 26,
          flowEfficiency: 0.65,
          lastStatusChangeAt: '2026-04-14',
          statusChangeCount: 3,
          inReviewSince: '2026-04-13',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Мария Кузнецова' }
        }
      },
      {
        id: '10025',
        key: 'B2B-25',
        fields: {
          summary: 'B2B: Вынести расчёты в отдельный сервис',
          sprintName: 'Sprint 9',
          storyPoints: 13,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-11',
          sprintStartDate: '2026-04-10',
          blockedSince: '2026-04-15',
          reopenCount: 1,
          timeInProgressHours: 30,
          timeInReviewHours: 6,
          cycleTimeHours: 70,
          flowEfficiency: 0.51,
          lastStatusChangeAt: '2026-04-18',
          statusChangeCount: 7,
          inReviewSince: '2026-04-17',
          status: { name: 'Blocked' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10026',
        key: 'B2B-26',
        fields: {
          summary: 'B2B: Добавить экспорт отчёта в PDF',
          sprintName: 'Sprint 9',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: true,
          createdAt: '2026-04-12',
          sprintStartDate: '2026-04-10',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 16,
          timeInReviewHours: 4,
          cycleTimeHours: 30,
          flowEfficiency: 0.67,
          lastStatusChangeAt: '2026-04-16',
          statusChangeCount: 4,
          inReviewSince: '2026-04-15',
          status: { name: 'In Review' },
          assignee: { displayName: 'Анна Смирнова' }
        }
      },
      {
        id: '10027',
        key: 'B2B-27',
        fields: {
          summary: 'B2B: Оптимизировать запросы к БД',
          sprintName: 'Sprint 9',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-13',
          sprintStartDate: '2026-04-10',
          blockedSince: undefined,
          reopenCount: 2,
          timeInProgressHours: 18,
          timeInReviewHours: 3,
          cycleTimeHours: 32,
          flowEfficiency: 0.66,
          lastStatusChangeAt: '2026-04-17',
          statusChangeCount: 5,
          inReviewSince: '2026-04-16',
          status: { name: 'Done' },
          assignee: { displayName: 'Пётр Петров' }
        }
      },
      {
        id: '10028',
        key: 'B2B-28',
        fields: {
          summary: 'B2B: Добавить health-check для API',
          sprintName: 'Sprint 10',
          storyPoints: 3,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-15',
          sprintStartDate: '2026-04-15',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 6,
          timeInReviewHours: 1,
          cycleTimeHours: 10,
          flowEfficiency: 0.7,
          lastStatusChangeAt: '2026-04-16',
          statusChangeCount: 1,
          inReviewSince: '2026-04-16',
          status: { name: 'Done' },
          assignee: { displayName: 'Мария Кузнецова' }
        }
      },
      {
        id: '10029',
        key: 'B2B-29',
        fields: {
          summary: 'B2B: Исправить ошибки авторизации',
          sprintName: 'Sprint 10',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: true,
          createdAt: '2026-04-16',
          sprintStartDate: '2026-04-15',
          blockedSince: undefined,
          reopenCount: 1,
          timeInProgressHours: 12,
          timeInReviewHours: 2,
          cycleTimeHours: 24,
          flowEfficiency: 0.58,
          lastStatusChangeAt: '2026-04-19',
          statusChangeCount: 3,
          inReviewSince: '2026-04-18',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10030',
        key: 'B2B-30',
        fields: {
          summary: 'B2B: Добавить поддержку новых тарифов',
          sprintName: 'Sprint 10',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-17',
          sprintStartDate: '2026-04-15',
          blockedSince: '2026-04-20',
          reopenCount: 2,
          timeInProgressHours: 20,
          timeInReviewHours: 5,
          cycleTimeHours: 48,
          flowEfficiency: 0.52,
          lastStatusChangeAt: '2026-04-23',
          statusChangeCount: 6,
          inReviewSince: '2026-04-22',
          status: { name: 'Blocked' },
          assignee: { displayName: 'Анна Смирнова' }
        }
      },
      {
        id: '10031',
        key: 'B2B-31',
        fields: {
          summary: 'B2B: Добавить агрегированный отчёт по клиентам',
          sprintName: 'Sprint 10',
          storyPoints: 13,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-18',
          sprintStartDate: '2026-04-15',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 26,
          timeInReviewHours: 6,
          cycleTimeHours: 60,
          flowEfficiency: 0.53,
          lastStatusChangeAt: '2026-04-25',
          statusChangeCount: 5,
          inReviewSince: '2026-04-24',
          status: { name: 'In Review' },
          assignee: { displayName: 'Пётр Петров' }
        }
      },
      {
        id: '10032',
        key: 'B2B-32',
        fields: {
          summary: 'B2B: Оптимизировать отчёт Executive Dashboard',
          sprintName: 'Sprint 11',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-20',
          sprintStartDate: '2026-04-20',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 10,
          timeInReviewHours: 2,
          cycleTimeHours: 18,
          flowEfficiency: 0.67,
          lastStatusChangeAt: '2026-04-22',
          statusChangeCount: 3,
          inReviewSince: '2026-04-21',
          status: { name: 'Done' },
          assignee: { displayName: 'Мария Кузнецова' }
        }
      },
      {
        id: '10033',
        key: 'B2B-33',
        fields: {
          summary: 'B2B: Добавить email-рассылку отчётов',
          sprintName: 'Sprint 11',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: true,
          createdAt: '2026-04-21',
          sprintStartDate: '2026-04-20',
          blockedSince: undefined,
          reopenCount: 1,
          timeInProgressHours: 16,
          timeInReviewHours: 4,
          cycleTimeHours: 32,
          flowEfficiency: 0.62,
          lastStatusChangeAt: '2026-04-25',
          statusChangeCount: 4,
          inReviewSince: '2026-04-24',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10034',
        key: 'B2B-34',
        fields: {
          summary: 'B2B: Исправить баг с фильтрацией по датам',
          sprintName: 'Sprint 11',
          storyPoints: 3,
          plannedInSprint: false,
          addedMidSprint: true,
          createdAt: '2026-04-22',
          sprintStartDate: '2026-04-20',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 6,
          timeInReviewHours: 1,
          cycleTimeHours: 12,
          flowEfficiency: 0.58,
          lastStatusChangeAt: '2026-04-23',
          statusChangeCount: 2,
          inReviewSince: '2026-04-23',
          status: { name: 'Done' },
          assignee: { displayName: 'Анна Смирнова' }
        }
      },
      {
        id: '10035',
        key: 'B2B-35',
        fields: {
          summary: 'B2B: Добавить поддержку многоязычности',
          sprintName: 'Sprint 11',
          storyPoints: 13,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-23',
          sprintStartDate: '2026-04-20',
          blockedSince: '2026-04-27',
          reopenCount: 2,
          timeInProgressHours: 30,
          timeInReviewHours: 5,
          cycleTimeHours: 72,
          flowEfficiency: 0.49,
          lastStatusChangeAt: '2026-04-30',
          statusChangeCount: 8,
          inReviewSince: '2026-04-29',
          status: { name: 'Blocked' },
          assignee: { displayName: 'Пётр Петров' }
        }
      },
      {
        id: '10036',
        key: 'B2B-36',
        fields: {
          summary: 'B2B: Ввести метрики по командам',
          sprintName: 'Sprint 12',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-25',
          sprintStartDate: '2026-04-25',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 18,
          timeInReviewHours: 4,
          cycleTimeHours: 34,
          flowEfficiency: 0.65,
          lastStatusChangeAt: '2026-04-29',
          statusChangeCount: 4,
          inReviewSince: '2026-04-28',
          status: { name: 'In Review' },
          assignee: { displayName: 'Мария Кузнецова' }
        }
      },
      {
        id: '10037',
        key: 'B2B-37',
        fields: {
          summary: 'B2B: Добавить матрицу рисков по проектам',
          sprintName: 'Sprint 12',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: true,
          createdAt: '2026-04-26',
          sprintStartDate: '2026-04-25',
          blockedSince: undefined,
          reopenCount: 1,
          timeInProgressHours: 12,
          timeInReviewHours: 3,
          cycleTimeHours: 24,
          flowEfficiency: 0.62,
          lastStatusChangeAt: '2026-05-01',
          statusChangeCount: 4,
          inReviewSince: '2026-04-30',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Иван Иванов' }
        }
      },
      {
        id: '10038',
        key: 'B2B-38',
        fields: {
          summary: 'B2B: Оптимизировать хранение исторических данных',
          sprintName: 'Sprint 12',
          storyPoints: 13,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-27',
          sprintStartDate: '2026-04-25',
          blockedSince: '2026-05-02',
          reopenCount: 1,
          timeInProgressHours: 28,
          timeInReviewHours: 6,
          cycleTimeHours: 80,
          flowEfficiency: 0.42,
          lastStatusChangeAt: '2026-05-05',
          statusChangeCount: 7,
          inReviewSince: '2026-05-04',
          status: { name: 'Blocked' },
          assignee: { displayName: 'Анна Смирнова' }
        }
      },
      {
        id: '10039',
        key: 'B2B-39',
        fields: {
          summary: 'B2B: Добавить рекомендации по планированию спринтов',
          sprintName: 'Sprint 12',
          storyPoints: 5,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-04-28',
          sprintStartDate: '2026-04-25',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 14,
          timeInReviewHours: 2,
          cycleTimeHours: 26,
          flowEfficiency: 0.62,
          lastStatusChangeAt: '2026-05-02',
          statusChangeCount: 3,
          inReviewSince: '2026-05-01',
          status: { name: 'Done' },
          assignee: { displayName: 'Пётр Петров' }
        }
      },
      {
        id: '10040',
        key: 'B2B-40',
        fields: {
          summary: 'B2B: Добавить мониторинг SLA по клиентам',
          sprintName: 'Sprint 13',
          storyPoints: 8,
          plannedInSprint: true,
          addedMidSprint: false,
          createdAt: '2026-05-01',
          sprintStartDate: '2026-05-01',
          blockedSince: undefined,
          reopenCount: 0,
          timeInProgressHours: 20,
          timeInReviewHours: 4,
          cycleTimeHours: 36,
          flowEfficiency: 0.67,
          lastStatusChangeAt: '2026-05-06',
          statusChangeCount: 4,
          inReviewSince: '2026-05-05',
          status: { name: 'In Progress' },
          assignee: { displayName: 'Иван Иванов' }
        }
      }
    ];

    return of({
      issues,
      total: issues.length
    });
  }
}

